export const projects = [
    {
        name: 'PrintForMe',
        description: 'Création d\'une extension chrome qui permet d\'automatiser la création de produit sur RedBubble grâce à ChatGPT',
        image: '/images/projects/printforme.png',
        link: 'https://chrome.google.com/webstore/detail/printforme/lfdchccbpeiddgghnbpeklknjoidhimc',
        displayLink: 'Télécharger l\'extension',
    },
    {
        name: 'RobbenSystem',
        description: 'Création de la landing page de Robben System, une entreprise qui gère les caisses enregistreuses des commerçants dans le sud ouest de la France',
        image: '/images/projects/robbensystem.png',
        link: 'https://robben.fr/',
        displayLink: 'robben.fr',
    },
    {
        name: 'myClubHouse',
        description: 'Création d\'un SaaS permettant de gérer de A à Z la création d\'un site internet pour un club de foot amateur',
        image: '/images/projects/myclubhouse.png',
        link: 'https://myclubhouse.fr/',
        displayLink: 'myclubhouse.fr',
    },
    {
        name: 'OP GREEN CONCEPT',
        description: 'Création du site vitrine de l\'entreprise OP GREEN CONCEPT, spécialisée dans l\'aménagement en gazon synthétique',
        image: '/images/projects/opgreenconcept.png',
        link: 'https://opgreenconcept.com/',
        displayLink: 'opgreenconcept.com',
    },
    {
        name: 'LR Parking',
        description: 'Création du site qui permet de voir les places de parking disponibles dans les parkings de la ville de La Rochelle en temps réel',
        image: '/images/projects/placeholder.png',
        link: 'https://lr-parking.vercel.app/',
        displayLink: 'lr-parking.vercel.app',
    },
    {
        name: 'OptiAnnonce',
        description: 'Création d\'un site qui permet de créer des annonces immobilières en quelques secondes grâce à l\'IA',
        image: '/images/projects/optiannonce.png',
        link: 'https://optiannonce.ai/',
        displayLink: 'optiannonce.ai',
    },
    {
        name: 'Tweet AI',
        description: "Création d'une extension chrome qui permet de créer ou répondre à des tweets grâce à ChatGPT directement depuis X",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
    {
        name: 'The Kingdom Checker',
        description: "Création d'un bot discord qui permet de gérer les abonnements et l'accès à la communauté The Kingdom de Pierre-Eliott Lallemant (Youtubeur de + de 100k abonnés)",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
    {
        name: 'NFT SHOW OFF',
        description: "Création d'un site qui permet de générer des bannières avec les NFT que l'on possède sur son wallet Ethereum",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
    {
        name: 'The Kingdom Tracker',
        description: "Création d'un bot discord qui permet de tracker les collections NFT tendances en fonction de leurs ventes dans les dernières heures",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
    {
        name: 'FCD2S - Seniors',
        description: "Création d'une app qui permet de gérer la catégorie seniors du club FCD2S. Gestion de la buvette, des amendes et des matchs en direct",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
    {
        name: 'TeddyGang',
        description: "Création d'une plateforme pour mint une collection de NFT sur la blockchain Polygon. J'ai aussi créé le smart contract associé",
        image: '/images/projects/placeholder.png',
        link: '',
        displayLink: '',
    },
]